modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="bettermc"
version="1.0.0"
displayName="bettermc"
credits="Made with MCreator! Texture sources: Minecraft Dungeons, and us!"
displayURL="http://www.coderqc.info"
authors="CoderQC & Robotkid0925"

[[dependencies.bettermc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




