modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="bettermc"
version="0.4.1"
displayName="BetterMC"
credits="Made with MCreator! Texture sources: Minecraft Dungeons, and us!"
displayURL="http://www.coderqc.info"
authors="CoderQC & Robotkid0925 & ScratchArts900"

[[dependencies.bettermc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




