modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="bettermc"
version="0.1.2"
displayName="bettermc"
credits="Made with MCreator!"
displayURL="http://www.coderqc.info"
authors="CoderQC, Robotkid0925, and Scratcharts900"

[[dependencies.bettermc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




